name: Android Build CI

# 触发条件：推送代码到 main 分支或从 main 分支发起 pull request 或者手动触发
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # 在最新的 Ubuntu 环境下运行

    steps:
      - uses: actions/checkout@v3 # 检出代码仓库
        with:
          fetch-depth: 0 # 获取所有历史记录，以便我们可以访问所有的提交

      - name: Set up JDK 17 # 设置 JDK 版本为 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate Debug Keystore File # 生成调试用的 keystore 文件
        run: |
          keytool -genkeypair -noprompt \
            -alias androiddebugkey \
            -dname "CN=Android Debug,O=Android,C=US" \
            -keystore debug.keystore \
            -storepass android \
            -keypass android \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000

      - name: Create local.properties file # 创建 local.properties 文件，设置 keystore 相关信息
        run: |
          echo "store_file=debug.keystore" > local.properties
          echo "store_pass=android" >> local.properties
          echo "key_alias=androiddebugkey" >> local.properties
          echo "key_pass=android" >> local.properties

      - name: Create gradle.properties file # 创建 gradle.properties 文件，设置 Gradle 和 Kotlin 编译选项
        run: |
          echo "#Kotlin" > gradle.properties
          echo "kotlin.code.style=official" >> gradle.properties
          echo "kotlin.daemon.jvmargs=-Xmx2048M" >> gradle.properties
          echo "" >> gradle.properties
          echo "#Gradle" >> gradle.properties
          echo "org.gradle.jvmargs=-Xmx8192M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options=\"-Xmx8192M\"" >> gradle.properties
          echo "systemProp.https.protocols=TLSv1,TLSv1.1,TLSv1.2,TLSv1.3" >> gradle.properties
          echo "" >> gradle.properties
          echo "#Android" >> gradle.properties
          echo "android.nonTransitiveRClass=true" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties

      - name: Extract App Version
        id: extract_version
        run: |
          APP_VERSION=$(grep -oP '^app-version\s*=\s*"\K[^"]+' gradle/libs.versions.toml | head -n 1)
          if [ -z "$APP_VERSION" ]; then
            echo "未能提取到版本号，请检查 gradle/libs.versions.toml 中是否存在 app-version = \"x.y.z\""
            exit 1
          fi
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          echo "::notice::提取到的版本号: $APP_VERSION"

      - name: Get Changes Since Last Release
        id: get_changes
        run: |
          LAST_TAG=$(git describe --tags --abbrev=0)
          echo "LAST_TAG=$LAST_TAG" >> $GITHUB_ENV
          CHANGES=$(git log ${LAST_TAG}..HEAD --pretty=format:"%h %s")
          echo "CHANGES=$CHANGES" >> $GITHUB_ENV
          echo "::notice::Changes since last release: $CHANGES"

      - name: Grant execute permission for gradlew # 给 gradlew 脚本添加执行权限
        run: chmod +x gradlew

      - name: Build Debug APK with Gradle # 使用 Gradle 构建 Debug APK
        run: ./gradlew assembleDebug --info

      - name: List APK files (for debugging) # 列出所有生成的 APK 文件（用于调试）
        run: find . -name "*.apk"

      - name: Move and Rename Debug APK # 移动并重命名 Debug APK 文件
        run: |
          mkdir -p artifact
          find . -name "*.apk" -exec mv {} artifact/VRCM-v${{ env.APP_VERSION }}.apk \;

      - name: Upload Debug Artifact # 上传构建好的 Debug APK 作为工作流产物
        uses: actions/upload-artifact@v4
        with:
          name: VRCM-DEBUG
          path: artifact/*.apk

      - name: Create Pre-Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.APP_VERSION }} # 使用提取出来的版本号
          release_name: 'VRCM DeBug ${{ env.APP_VERSION }}' # 发布名称
          body: ${{ env.CHANGES }} # 自动获取的更改内容
          draft: false
          prerelease: true # 设置为预发布

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing its ID to get its outputs object, which include a `upload_url`.
          asset_path: ./artifact/VRCM-v${{ env.APP_VERSION }}.apk # 使用带有版本号的APK文件路径
          asset_name: VRCM-v${{ env.APP_VERSION }}.apk # APK 文件名
          asset_content_type: application/vnd.android.package-archive
